title: Open Receipt OCR
description: A powerful, flexible, and extensible OCR platform for receipts and documents
theme: jekyll-theme-cayman
baseurl: /open-receipt-ocr

# Navigation
nav_order: 1
nav_exclude: false

# Search
search_enabled: true
heading_anchors: true

# Collections
collections:
  guides:
    output: true
    permalink: /guides/:path/
