source "https://rubygems.org"

gem "github-pages", "~> 228", group: :jekyll_plugins
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-seo-tag", "~> 2.6"
  gem "jekyll-sitemap", "~> 1.4"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gemspec so it doesn't get upgraded
# This is to prevent gems that require an older `http_parser.rb` version
# from forcing an update to the newest (incompatible) `http_parser.rb`.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
